### PR TITLE
fingerubung03

### PR DESCRIPTION
**Pull request by syahidhusein**

### CODE REVIEW

**Comment by Lizoug** [comment]
I reviewed the Code. Everything is fine 👍 

First of all i like your commit comments, which are really nice and we can see the new patterns.

You just added 3 new patterns but they are working well. I like the Idea of having a new file  dailiza-bot/neutral_resp.py and the option to exit the chat.

If I would need to add some suggestion, it would be nice if we just lowercase the input of the user so that we can just avoid  a regex like [Ww]...

**Comment by syahidhusein** [comment]
@florian-huber pull request ready to merge 👍

**Review by Lizoug — APPROVED** [review]
Ready to merge!

**Comment by Lizoug** [comment]
@florian-huber pull request ready to merge

**Review by florian-huber — APPROVED** [review]
Looks good and will be merged!

**Pull request merged**
