### PR TITLE
New regex pattern

### PR DESCRIPTION
**Pull request by till-teb**
added 4 new pattern:
 
- I want ....
- I m learning ...
- How is ....
- Do you like ...

### CODE REVIEW

**Review by syahidhusein — APPROVED** [review]
Code looks good 👍 
One suggestion tho, converting the user_input to lowercase with .lower() would eliminate the need to include patterns like [Ii] and [Ww].
Other than that, good job!

**Comment by miriam-agrawala** [comment]
I like your changes!

Depending on the input to the last question you added, it might happen that Dailiza's answer will begin with a lower-case letter, since one of the possible answers starts with the word that was typed in by the user. Just a small "flaw" though :)

Also, I like that the last question you added isn't actually about finding out something that concerns you, but about finding out about something that interests Dailiza!

**Review by miriam-agrawala — APPROVED** [review]
I like your changes!

Depending on the input to the last question you added, it might happen that Dailiza's answer will begin with a lower-case letter, since one of the possible answers starts with the word that was typed in by the user. Just a small "flaw" though, could be fixed by adding .upper() for the first letter of the output :)

Also, I like that the last question you added isn't actually about finding out something that concerns you, but about finding out about something that interests Dailiza!

**Comment by miriam-agrawala** [comment]
@florian-huber pull request ready to be merged

**Pull request merged**
